### ISSUE TITLE
build failed ： undefined xxx

### ISSUE THREAD

**Issue by ZetaChow** [muka/go-bluetooth#85] opened 2019-09-05 03:29 UTC
● ~ » cd $GOPATH/src/github.com/muka/go-bluetooth && make build                         
CGO_ENABLED=0 go build -o go-bluetooth ./main.go
hw/linux/hci/hci.go:7:9: undefined: socket.Down
hw/linux/hci/hci.go:12:9: undefined: socket.Up
hw/linux/hci/hci.go:17:9: undefined: socket.List

**Comment by muka** [comment] 2019-09-05 03:33
Do you have dependencies installed?

Try with `go get -u -v ./...`

**Comment by ZetaChow** [comment] 2019-09-05 05:36
I try `go get -u -v ./...`
other error show:
bluez/profile/network/gen_Network1.go:290:50: syntax error: unexpected upon, expecting comma or )
bluez/profile/network/gen_Network1.go:292:20: syntax error: unexpected either at end of statement

**Comment by muka** [comment] 2019-09-05 08:20
It was a bug. I will fix the generation but in the meanwhile this commit should fix it

**Comment by muka** [comment] 2019-09-13 07:02
Closing, let me know if the issue is still there. Thank you

**Closed by muka** 2019-09-13 07:02 UTC
